version: '3.8'

services:
  db:
      image: postgres
      environment:
        POSTGRES_DB: nest
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
      ports:
        - "5434:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8080"
  # db-test:
  #     image: postgres
  #     environment:
  #       POSTGRES_DB: nest-test
  #       POSTGRES_USER: root
  #       POSTGRES_PASSWORD: root
  #     ports:
  #       - "5435:5432"
